/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_hotring_util_PhysicalAddress */

#ifndef _Included_com_hotring_util_PhysicalAddress
#define _Included_com_hotring_util_PhysicalAddress
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_hotring_util_PhysicalAddress
 * Method:    callAddress
 * Signature: (Ljava/lang/Object;)J
 */
JNIEXPORT jlong JNICALL Java_com_hotring_util_PhysicalAddress_callAddress
  (JNIEnv *, jclass, jobject);

#ifdef __cplusplus
}
#endif
#endif
